import React from 'react'

import { useState, useEffect } from 'react'
import { Loader , Card , FormField } from '../components'

const RanderCards = ({data , title}) => {
 if(data.lenght > 0) {
    return data.map((post) => <Card key={post.id} {...post}/>)
 }else;
    return <h1> {title} </h1>
}

const Home = () => {

  // Building a State 
  const [loading , setLoading ] = useState(false)
  const [allPosts , setAllPosts ] = useState(null)
  const [searchText, setSearchText] = useState('')

  return (
    <section className='bom1 max-w-7xl mx-auto'>

      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>The Comunity Showcase</h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>Browse Through a Collection of imaginative and visually stunning images generated by AI</p>
      </div>

      <div className='mt-16 '>
        <FormField/>
      </div>
D
      <div className='mt-10'>
          {loading ? (
            <div className='flex justify-center items-center'>
              <Loader/>
            </div>
          ) : (
              <div>

                {searchText ? (
                  <RanderCards
                  data={[]}
                  title="post 1"
                  />
                ) : (

                  <RanderCards 
                  data={[]}
                  title="post 2"
                  />
                )}

              </div>
          )}
      </div>

    </section>
  )
}

export default Home